export const TYPE_PROPERTY = {
  TEXTBOX: "TEXTBOX",
  COMBOBOX: "COMBOBOX",
  TABLE: "TABLE",
  TEXTAREA: "TEXTAREA",
  DATE: "DATE",
  CHECKBOX: "CHECKBOX",
  RADIO: "RADIO",
  DATETIME: "DATETIME",
  NUMBERIC: "NUMBERIC",
  MULTISELECT: "MULTISELECT",
  TOGGLE: 'TOGGLE'
}
